debug: false

server:
  port: 9999

spring:
  application:
    name: zuul-gateway-v1
  cloud:
    refresh:
      extra-refreshable:
        - none
    inetutils:
      preferred-networks:
        - 192.168

eureka:
  client:
    service-url:
      defaultZone: http://10.64.104.106:34000/eureka
  instance:
    prefer-ip-address: true

# zuul.* ZuulProperties.java
zuul:
#  prefix:
  servletPath: /api #default /zuul
  ignore-local-service: false

  retryable: true
  ribbon-isolation-strategy: THREAD # default SEMAPHORE
  initial-stream-buffer-size: 8192 # default 8192 8M

  add-proxy-headers: true
  add-host-header: true
  ignore-security-headers: true

  ignored-patterns:
#    - '*-provider-*'

  ignored-services:
    - 'eureka-server'
#    - '*-provider-*'

  semaphore:
    max-semaphores: 100 #default 100
  thread-pool:
    thread-pool-key-prefix: zuul-thread-example
    use-separate-thread-pools: true # default false

#  routes: #map

# ZuulRouteApplicationContextInitializer
  ribbon:
    eager-load:
      enabled: true

# 指定禁用过滤器 simple-class-name.filter-type.disable:true
#  PreRequestLogFilter:
#    pre:
#      disable: false

logging:
  path: ${user.home}/logs/${spring.application.name}/${server.port}
