debug: false

server:
  port: 9884

spring:
  application:
    name: config-server
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
    config:
      server:
        git:
          uri: ssh://yate@localhost:22/home/yate/code-repo/demo-config.git
          username: yate
          password: qwe123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9881/eureka,http://localhost:9880/eureka
  instance:
    prefer-ip-address: true

logging:
  path: ${user.home}/logs/${spring.application.name}/${server.port}
