debug: false

server:
  port: 9885

spring:
  application:
    name: order-provider
  cloud:
    refresh:
      extra-refreshable:
        - none
    inetutils:
      preferred-networks:
        - 192.168
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
    log:
      slf4j:
        enabled: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root123
      pool-name: demo-ds
      connection-test-query: SELECT 1
      connection-timeout: 60000
      auto-commit: false
      minimum-idle: 1
      max-lifetime: 1
      maximum-pool-size: 8
      data-source-properties:
        cache-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true

mybatis:
  type-aliases-package: one.yate.spring.cloud.provider.matedata.entity
  mapper-locations:
    - classpath*:/mybatis/mapper/**/*.xml
  executor-type: REUSE
  configuration:
      cache-enabled: true
      lazy-loading-enabled: false
      aggressive-lazy-loading: false
      multiple-result-sets-enabled: true
      use-column-label: true
      use-generated-keys: true
      auto-mapping-behavior: FULL
      default-statement-timeout: 30
      map-underscore-to-camel-case: true
      default-fetch-size: 10

##mybatis
#mybatis-plus:
#  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: one.yate.spring.cloud.provider.matedata.entity
#  global-config:
#    #刷新mapper 调试神器
#    db-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: id_worker
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: mysql
#    refresh: true
#      #自定义填充策略接口实现
#      #meta-object-handler: com.baomidou.springboot.xxx
#      #自定义SQL注入器
#      #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9880/eureka,http://localhost:9881/eureka
  instance:
    prefer-ip-address: true

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true

logging:
  path: ${user.home}/logs/${spring.application.name}/${server.port}
